url: "https://www.intptr.im/blog"
baseurl: "/blog"
timezone: "Asia/Shanghai"
permalink: "/post/:title.html"
kramdown:
  input: GFM
gems:
  - jekyll-sitemap
  - jekyll-mentions
navs:
  - name: "Friends"
    url: "/friends.html"
  - name: "About"
    url: "/about.html"
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
