url: "http://www.intptr.im/blog"
baseurl: "/blog"
timezone: "Asia/Shanghai"
permalink: "/post/:title.html"
kramdown:
  input: GFM
  smart_quotes: apos,apos,quot,quot
gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
